Revert "US3987 remove dependencies on jquery-migrate"
This reverts commit 6fd94aaff232d680e9094f67b52f44449092158d.

Fixes error:

Error: Mismatched anonymous define() module: undefined
http://requirejs.org/docs/errors.html#mismatch